import GalleryClient from "./GalleryClient";

// 1. METADATA: This is what Google sees!
export const metadata = {
  title: "Infinite Inspiration Gallery", // Shows as "Infinite Inspiration Gallery | NestImage"
  description:
    "Browse our endless collection of random high-quality images. Download free stock photos, wallpapers, and art generated by the community.",
  keywords: [
    "random gallery",
    "inspiration",
    "infinite scroll",
    "bulk image download",
    "free stock photos",
  ],
};

// 2. SERVER COMPONENT: Renders the Client Component
export default function GalleryPage() {
  return <GalleryClient />;
}
